#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	#exit 1
  fi
  echo
  echo 'finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo
}

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_COM238_fase1 fase1_star1_COM238.mod
do_one inlist_COM338_fase1 fase1_star1_COM338.mod
do_one inlist_COM438_fase1 fase1_star1_COM438.mod
#do_one inlist_COM238_fase2 fase2_star2_COM238.mod
#do_one inlist_COM338_fase2 fase2_star2_COM338.mod
#do_one inlist_COM438_fase2 fase2_star2_COM438.mod

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists'

